package com.productivity.testwind.Screens.Settings

import com.productivity.testwind.Imports.Utils.Log.*
import com.productivity.testwind.Imports.Utils.Generic_list.*
import com.productivity.testwind.Imports.Utils.Renames.*
import com.productivity.testwind.Imports.Utils.SaveData.*
import com.productivity.testwind.Imports.Utils.AppsAndDevice.*
import com.productivity.testwind.Imports.Utils.NavControl.*
import com.productivity.testwind.Screens.Settings.LogScreen.*
import com.productivity.testwind.Screens.*
import com.productivity.testwind.Imports.Utils.ToX.*
import com.productivity.testwind.Imports.Utils.String.*
import androidx.compose.foundation.layout.*
import androidx.compose.material.icons.Icons
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.graphics.Color
import kotlinx.coroutines.delay
import android.service.notification.NotificationListenerService
import androidx.compose.foundation.rememberScrollState
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.Modifier
import androidx.compose.foundation.*
import com.productivity.testwind.Imports.*
import com.productivity.testwind.*
import com.productivity.testwind.Imports.Utils.*
import androidx.compose.ui.unit.*
import androidx.compose.foundation.shape.*
import androidx.compose.ui.text.style.*
import androidx.compose.ui.*
import androidx.compose.foundation.lazy.*
import com.google.android.gms.maps.model.*
import com.google.maps.android.compose.*
import com.productivity.testwind.Imports.UI_visible.*
import android.os.*
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.input.*
import androidx.compose.material3.pulltorefresh.*
import androidx.compose.material3.pulltorefresh.PullToRefreshDefaults.Indicator      
import androidx.compose.ui.text.rememberTextMeasurer
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.platform.LocalLayoutDirection
import android.provider.Settings
